# Generated by Django 5.1.2 on 2024-11-07 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickertype',
            name='image',
        ),
        migrations.AddField(
            model_name='sticker',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 11, 7, 2, 3, 40, 43116, tzinfo=datetime.timezone.utc), upload_to='core/media'),
            preserve_default=False,
        ),
    ]
