# Generated by Django 5.1.2 on 2024-11-01 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_remove_user_date_joined_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ph_num',
            field=models.CharField(blank=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+959XXXXXXXX'.", regex='^\\+959\\d{9}$')]),
        ),
    ]
